#!/bin/bash

# Veapysh: is a terminal utility available on Linux systems for automated administration of basic scripts.
# License: GNU General Public License v2.0
# Developed by: Angel Gabriel Mortera Gual
# Github project: URL

# Options
VERSION_VP="Veapysh 0.0.1"


case "$1" in
-h|--help)
	cat /etc/veapysh/Configuration/veapysh_help.txt	
	;;
-l|--list)
	sudo /etc/veapysh/Configuration/veapysh_viewprocess.sh
	;;
-v|--version)
        echo "$VERSION_VP"
        ;;  
*)
	sudo python3 /etc/veapysh/Configuration/veapysh_configuration.py
esac

