#!/bin/bash

# Veapysh: is a terminal utility available on Linux systems for automated administration of basic scripts.
# License: GNU General Public License v2.0
# Developed by: Angel Gabriel Mortera Gual
# Github project: https://github.com/TheWatcherMultiversal/Veapysh

# Options
VERSION_VP="Veapysh v1.0.1"

set -e

case "$1" in
-h|--help)
        cat /etc/veapysh/Configuration/veapysh_help.txt 
        ;;
-l|--list)
        sh /usr/share/veapysh/veapysh-requeriments.sh
        sudo /etc/veapysh/Configuration/veapysh_viewprocess.sh -l
        ;;
-v|--version)
        echo "$VERSION_VP"
        ;;  
*)
        sh /usr/share/veapysh/veapysh-requeriments.sh
        sudo python3 /etc/veapysh/Configuration/veapysh_configuration.py
esac
